services:

  mwb-mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"  # Для дебага, web ui для просмотра писем
    restart: unless-stopped
    networks:
      - mwb-net

  mwb-db:
    image: postgres:16-alpine
    env_file:
      - ../.env
    ports:
      - "5432:5432"  # Для дебага
    volumes:
      - mwb-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: >
        /bin/sh -c 'pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"'
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    networks:
      - mwb-net

  mwb-redis:
    image: redis:7-alpine
    env_file:
      - ../.env
    ports:
      - "6379:6379"  # Для дебага
    command: redis-server --requirepass $REDIS_PASSWORD
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - mwb-net

  mwb-build-image:
    build:
      context: ..
      dockerfile: deploy/docker/service.Dockerfile
    image: mwb-service:latest
    restart: "no"

  mwb-migrate:
    image: mwb-service:latest
    env_file:
      - ../.env
    depends_on:
      mwb-db:
        condition: service_healthy
      mwb-build-image:
        condition: service_completed_successfully
    command: ["python", "-m", "invoke", "migrate-apply"]
    restart: "no"
    networks:
      - mwb-net

  mwb-worker:
    image: mwb-service:latest
    env_file:
      - ../.env
    depends_on:
      mwb-redis:
        condition: service_healthy
      mwb-build-image:
        condition: service_completed_successfully
    command: ["python", "-m", "invoke", "worker"]
    restart: unless-stopped
    networks:
      - mwb-net

  mwb-beat:
    image: mwb-service:latest
    env_file:
      - ../.env
    depends_on:
      mwb-redis:
        condition: service_healthy
      mwb-build-image:
        condition: service_completed_successfully
    command: [".venv/bin/python", "-m", "invoke", "beat"]
    restart: unless-stopped
    networks:
      - mwb-net

  mwb-app:
    image: mwb-service:latest
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    depends_on:
      mwb-migrate:
        condition: service_completed_successfully
      mwb-build-image:
        condition: service_completed_successfully
    command: ["gunicorn", "-k", "uvicorn.workers.UvicornWorker", "-c", "deploy/config/gunicorn_conf.py", "app.main:app"]
    restart: unless-stopped
    networks:
      - mwb-net

volumes:
  mwb-pgdata:

networks:
  mwb-net:
    driver: bridge
